use crate::campaign::slugify;
use crate::Result;
use std::path::{Path, PathBuf};
use std::process::{Child, Command};
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::Duration;

const BASE_PORT: u16 = 8100;

static SHUTDOWN: AtomicBool = AtomicBool::new(false);

extern "C" fn on_sigint(_: libc::c_int) {
    SHUTDOWN.store(true, Ordering::SeqCst);
}

/// Multi-campaign hosting as a directory of single-tenant instances: one
/// `magehand serve` child per campaign subdir, cwd set to that dir. No campaign
/// state is ever shared in-process, so a bug in one table can't leak another
/// table's secrets.
pub(crate) fn cmd_host(args: &[String]) -> Result<()> {
    if args.first().map(String::as_str) == Some("new") {
        return cmd_new(&args[1..]);
    }
    let data_dir = flag_val(args, "--data-dir").unwrap_or(".").to_string();
    let public_url = flag_val(args, "--public-url").map(|u| u.trim_end_matches('/').to_string());
    let campaigns = scan_campaigns(&data_dir)?;
    if campaigns.is_empty() {
        return Err(format!(
            "no campaigns under {data_dir} — create one with `magehand host new <name> --data-dir {data_dir}`"
        )
        .into());
    }
    if public_url.is_none() {
        eprintln!("warning: no --public-url — join QR links will use LAN addresses, not your domain");
    }

    write_caddyfile(&data_dir, &campaigns, public_url.as_deref())?;
    unsafe {
        libc::signal(libc::SIGINT, on_sigint as *const () as libc::sighandler_t);
        libc::signal(libc::SIGTERM, on_sigint as *const () as libc::sighandler_t);
    }

    let exe = std::env::current_exe()?;
    println!("magehand host — {} campaign(s)\n", campaigns.len());
    let mut children: Vec<(usize, Option<Child>)> = (0..campaigns.len()).map(|i| (i, None)).collect();
    for c in &campaigns {
        println!("  /c/{}/  →  127.0.0.1:{}   ({})", c.slug, c.port, c.dir.display());
    }
    println!("\nreverse-proxy config written to {data_dir}/Caddyfile.magehand — `caddy run` with it (or import it).");
    println!("Ctrl-C stops every campaign.\n");

    // supervise: spawn, then respawn anything that dies (1s backoff via the loop tick)
    while !SHUTDOWN.load(Ordering::SeqCst) {
        for (i, slot) in &mut children {
            let dead = match slot {
                Some(child) => child.try_wait()?.is_some(),
                None => true,
            };
            if dead && !SHUTDOWN.load(Ordering::SeqCst) {
                let c = &campaigns[*i];
                if slot.is_some() {
                    eprintln!("host: campaign `{}` exited — respawning", c.slug);
                }
                *slot = Some(spawn_serve(&exe, c, public_url.as_deref())?);
            }
        }
        std::thread::sleep(Duration::from_secs(1));
    }
    for (_, slot) in &mut children {
        if let Some(child) = slot {
            let _ = child.kill();
            let _ = child.wait();
        }
    }
    println!("host: stopped");
    Ok(())
}

struct Campaign {
    slug: String,
    dir: PathBuf,
    port: u16,
}

/// A campaign is any subdir with a `sources/` inside — the same marker
/// `ensure_vault` trusts. Ports are assigned in sorted-slug order; they can
/// shift when campaigns are added, but nothing user-facing carries a port
/// (links go through the /c/<slug>/ proxy route).
fn scan_campaigns(data_dir: &str) -> Result<Vec<Campaign>> {
    let mut slugs: Vec<(String, PathBuf)> = std::fs::read_dir(data_dir)
        .map_err(|e| format!("can't read data dir {data_dir}: {e}"))?
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.is_dir() && p.join(crate::SOURCES_DIR).is_dir())
        .filter_map(|p| p.file_name().map(|n| (n.to_string_lossy().into_owned(), p.clone())))
        .collect();
    slugs.sort();
    Ok(slugs
        .into_iter()
        .enumerate()
        .map(|(i, (slug, dir))| Campaign { slug, dir, port: BASE_PORT + u16::try_from(i).unwrap_or(0) })
        .collect())
}

fn spawn_serve(exe: &Path, c: &Campaign, public_url: Option<&str>) -> Result<Child> {
    let mut cmd = Command::new(exe);
    cmd.arg("serve").arg("--port").arg(c.port.to_string()).current_dir(&c.dir);
    if let Some(url) = public_url {
        cmd.arg("--public-base").arg(format!("{url}/c/{}", c.slug));
    }
    Ok(cmd.spawn()?)
}

fn write_caddyfile(data_dir: &str, campaigns: &[Campaign], public_url: Option<&str>) -> Result<()> {
    let site = public_url
        .and_then(|u| u.split("://").nth(1))
        .unwrap_or(":8443")
        .to_string();
    let mut out = format!(
        "# generated by `magehand host` — tokens ride in first-visit URLs, so keep\n\
         # query strings out of access logs\n\
         {site} {{\n\tlog {{\n\t\tformat filter {{\n\t\t\trequest>uri query {{\n\t\t\t\tdelete t\n\t\t\t}}\n\t\t}}\n\t}}\n"
    );
    for c in campaigns {
        out.push_str(&format!(
            "\tredir /c/{slug} /c/{slug}/ 308\n\thandle_path /c/{slug}/* {{\n\t\treverse_proxy 127.0.0.1:{port}\n\t}}\n",
            slug = c.slug,
            port = c.port
        ));
    }
    out.push_str("}\n");
    let path = format!("{data_dir}/Caddyfile.magehand");
    std::fs::write(&path, out)?;
    Ok(())
}

/// `magehand host new <name> [--data-dir d]` — vault skeleton only; the child
/// serve's ensure_vault fills in the campaign dirs on first start.
fn cmd_new(args: &[String]) -> Result<()> {
    let name: Vec<&String> = args.iter().take_while(|a| !a.starts_with("--")).collect();
    if name.is_empty() {
        return Err("usage: magehand host new <name> [--data-dir <dir>]".into());
    }
    let slug = slugify(&name.iter().map(|s| s.as_str()).collect::<Vec<_>>().join(" "));
    if slug.is_empty() {
        return Err("name needs at least one letter or number".into());
    }
    let data_dir = flag_val(args, "--data-dir").unwrap_or(".");
    let dir = Path::new(data_dir).join(&slug);
    if dir.join(crate::SOURCES_DIR).is_dir() {
        return Err(format!("campaign already exists: {}", dir.display()).into());
    }
    std::fs::create_dir_all(dir.join(crate::SOURCES_DIR).join("house"))?;
    println!("created {}", dir.display());
    println!("drop rulebooks under {}/sources/, then (re)start `magehand host`", dir.display());
    Ok(())
}

fn flag_val<'a>(args: &'a [String], flag: &str) -> Option<&'a str> {
    args.iter().position(|a| a == flag).and_then(|i| args.get(i + 1)).map(String::as_str)
}
